In [15]:
import pandas as pd

## Read Data

In [16]:
df = pd.read_csv("https://raw.githubusercontent.com/RBellaApriliaDamayanti22/project_pendat/main/Data.csv")
df

No  Weight  Length  Circumference Grade
0    1   486.5    14.0           27.0     A
1    2   388.4    12.0           26.0     A
2    3   493.7    12.0           26.5     A
3    4   342.5    10.0           24.3     A
4    5   401.5    11.0           25.0     A
..  ..     ...     ...            ...   ...
62  63   448.3    12.5           26.0     B
63  64   289.2    11.0           21.8     B
64  65   381.4    12.5           24.0     B
65  66   298.1    11.3           22.5     B
66  67   420.5    12.6           26.0     B

[67 rows x 5 columns]

## Exploration Data

In [27]:
df.head()

No  Weight  Length  Circumference Grade
0   1   486.5    14.0           27.0     A
1   2   388.4    12.0           26.0     A
2   3   493.7    12.0           26.5     A
3   4   342.5    10.0           24.3     A
4   5   401.5    11.0           25.0     A

In [5]:
df[["No","Weight","Length","Circumference"]].agg(['min','max'])

No  Weight  Length  Circumference
min   1   241.0    10.0           21.5
max  67   571.9    15.4           29.9

In [6]:
df.Grade.value_counts()

A    34
B    33
Name: Grade, dtype: int64

## preprocessing data

In [7]:
 X = df.drop(columns="Grade")
 y = df.Grade

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [9]:
le.inverse_transform(y)

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B'], dtype=object)

In [10]:
labels = pd.get_dummies(df.Grade).columns.values.tolist()
labels

['A', 'B']

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[0.        , 0.74191599, 0.74074074, 0.6547619 ],
       [0.01515152, 0.4454518 , 0.37037037, 0.53571429],
       [0.03030303, 0.76367483, 0.37037037, 0.5952381 ],
       [0.04545455, 0.3067392 , 0.        , 0.33333333],
       [0.06060606, 0.4850408 , 0.18518519, 0.41666667],
       [0.07575758, 0.30643699, 0.46296296, 0.29761905],
       [0.09090909, 0.29434875, 0.46296296, 0.29761905],
       [0.10606061, 0.44394077, 0.44444444, 0.55952381],
       [0.12121212, 0.63674826, 0.62962963, 0.69047619],
       [0.13636364, 0.32789362, 0.37037037, 0.36904762],
       [0.15151515, 0.58779087, 0.61111111, 0.5952381 ],
       [0.16666667, 0.54699305, 0.5       , 0.73809524],
       [0.18181818, 1.        , 1.        , 1.        ],
       [0.1969697 , 0.5098217 , 0.55555556, 0.55952381],
       [0.21212121, 0.58023572, 0.53703704, 0.63095238],
       [0.22727273, 0.69839831, 0.75925926, 0.67857143],
       [0.24242424, 0.25143548, 0.37037037, 0.33333333],
       [0.25757576, 0.68359021,

In [12]:
X.shape, y.shape

((67, 4), (67,))

In [13]:
le.inverse_transform(y)

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B'], dtype=object)

In [14]:
labels = pd.get_dummies(df.Grade).columns.values.tolist()
labels

['A', 'B']

## Normalisasi MinMax Scaler

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[0.        , 0.74191599, 0.74074074, 0.6547619 ],
       [0.01515152, 0.4454518 , 0.37037037, 0.53571429],
       [0.03030303, 0.76367483, 0.37037037, 0.5952381 ],
       [0.04545455, 0.3067392 , 0.        , 0.33333333],
       [0.06060606, 0.4850408 , 0.18518519, 0.41666667],
       [0.07575758, 0.30643699, 0.46296296, 0.29761905],
       [0.09090909, 0.29434875, 0.46296296, 0.29761905],
       [0.10606061, 0.44394077, 0.44444444, 0.55952381],
       [0.12121212, 0.63674826, 0.62962963, 0.69047619],
       [0.13636364, 0.32789362, 0.37037037, 0.36904762],
       [0.15151515, 0.58779087, 0.61111111, 0.5952381 ],
       [0.16666667, 0.54699305, 0.5       , 0.73809524],
       [0.18181818, 1.        , 1.        , 1.        ],
       [0.1969697 , 0.5098217 , 0.55555556, 0.55952381],
       [0.21212121, 0.58023572, 0.53703704, 0.63095238],
       [0.22727273, 0.69839831, 0.75925926, 0.67857143],
       [0.24242424, 0.25143548, 0.37037037, 0.33333333],
       [0.25757576, 0.68359021,

In [16]:
X.shape, y.shape

((67, 4), (67,))

## Split Data

In [17]:
# membagi data menjadi data testing(20%) dan training(80%)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((53, 4), (14, 4), (53,), (14,))

## Model

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from numpy import array

## KNN

In [20]:
metode1 = KNeighborsClassifier(n_neighbors=3)
metode1.fit(X_train, y_train)
print(metode1.score(X_train, y_train))
print(metode1.score(X_test, y_test))
y_pred = metode1.predict(scaler.transform(array([[0.0,12.8,5.0,4.7]])))
le.inverse_transform(y_pred)[0]

0.9622641509433962
0.9285714285714286


'A'

## Gaussian Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB

metode2 = GaussianNB()
metode2.fit(X_train, y_train)
print(metode2.score(X_train, y_train))
print(metode2.score(X_test, y_test))
y_pred = metode2.predict(array([[0.0,12.8,5.0,4.7]]))
le.inverse_transform(y_pred)[0]


0.9622641509433962
0.9285714285714286


'B'

## D T

k = 3 

karena mendapatkan nilai tertinggi

In [22]:
from sklearn import tree

metode3 = tree.DecisionTreeClassifier(criterion="gini")
metode3.fit(X_train, y_train)
print(metode3.score(X_train, y_train))
print(metode3.score(X_test, y_test))
y_pred = metode3.predict(array([[0.0,12.8,5.0,4.7]]))
le.inverse_transform(y_pred)[0]

1.0
1.0


'A'

## Export 



*   Label Encoder
*   Scaler
*   Model



In [23]:
from sklearn.utils.validation import joblib
# label encoder
joblib.dump(le, "le.save") 

# scaler
joblib.dump(scaler, "scaler.save") 

# model
joblib.dump(metode1, "nb.joblib")
joblib.dump(metode2, "knn.joblib")
joblib.dump(metode3, "tree.joblib")

['tree.joblib']

In [22]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X = df.drop(labels = 'Grade',axis = 1)
y = df['Grade'].map({'A': 0, 'B': 1})
   
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 88)

le = preprocessing.LabelEncoder()
le.fit(y)
y = le.transform(y)
 
y

le.inverse_transform(y)

labels = pd.get_dummies(df.Grade).columns.values.tolist()

labels

scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

X

X.shape, y.shape

le.inverse_transform(y)

labels = pd.get_dummies(df.Grade).columns.values.tolist()
    
labels

scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
X

X.shape, y.shape 

((67, 4), (67,))

In [19]:
scaler = StandardScaler()

In [20]:
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [33]:
from sklearn.utils.validation import joblib
# label encoder
joblib.dump(le, "le.save") 

# scaler
joblib.dump(scaler, "scaler.save") 



['scaler.save']

In [44]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [45]:
# Build a function for choosing reasonable K value

error_rates = []

for k in range(1,30):
    knn_model = KNeighborsClassifier(n_neighbors=k)
    knn_model.fit(scaled_X_train,y_train)
    y_knn_predict = knn_model.predict(scaled_X_test)
    
    error_k = 1 - accuracy_score(y_test,y_knn_predict)
    
    error_rates.append(error_k)

In [46]:
knn_model = KNeighborsClassifier(n_neighbors=5)

In [47]:
knn_model.fit(scaled_X_train,y_train)

KNeighborsClassifier()

In [48]:
y_knn_predict = knn_model.predict(scaled_X_test)

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_knn_predict))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.92      0.96        13

    accuracy                           0.96        27
   macro avg       0.97      0.96      0.96        27
weighted avg       0.97      0.96      0.96        27



In [51]:
skor_akurasi = round(100 * accuracy_score(y_test,y_knn_predict))

In [52]:
print(skor_akurasi)

96


In [1]:
from sklearn.utils.validation import joblib
 

# model

joblib.dump(metode2, "knn2.joblib")


NameError: ignored

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
metode1 = LogisticRegression()

In [31]:
metode1.fit(scaled_X_train,y_train)

LogisticRegression()

In [32]:
metode1.coef_

array([[ 2.24843984,  0.054756  , -0.23852122, -1.08876454]])

In [33]:
y_pred = metode1.predict(scaled_X_test)
from sklearn.metrics import classification_report, plot_confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.92      0.92      0.92        13

    accuracy                           0.93        27
   macro avg       0.93      0.93      0.93        27
weighted avg       0.93      0.93      0.93        27



In [36]:
from sklearn.metrics import accuracy_score
akurasi = round(100 * accuracy_score(y_test, y_pred))


In [37]:
print(akurasi)

93


In [34]:
from sklearn.utils.validation import joblib


# model
joblib.dump(metode1, "LR.joblib")

['LR.joblib']